### ISSUE TITLE
Be able to retrigger testing-farm requests for chroots

### ISSUE THREAD

**Issue by kwk** [fedora-llvm-team/llvm-snapshots#416]
I believe that with the dependency on testing-farm and daily new composes of our distros we have a need to restart testing-farm requests through an issue comment like `/retest fedora-40-ppc64le fedora-40-s390x fedora-rawhide-s390x`.

For this to work I imagine this:

- [ ] #501

- [x] A GitHub workflow that reacts to **new** comments on issues made by members of this [`llvm-toolset-engineers` team](https://github.com/orgs/fedora-llvm-team/teams/llvm-toolset-engineers). The workflow should parse comments if they begin with `/retest` followed by multiple arguments. As soon as this is the case I want to move on from within a Python.
  * The only thing that the workflow should do itself is to leave a comment reaction on the triggering comment. 

- [x] For the parsing and verification of the comment I want to move as quickly to a python script as possible.

- [x] The arguments of the `/retest` comment should be inspected and checked if they are *chroots we care about*.
  * We have [`snapshot_manager.util.expect_chroot`](https://github.com/fedora-llvm-team/llvm-snapshots/blob/a597c30d9599811318f95fa47447c591105df6d0/snapshot_manager/snapshot_manager/util.py#L173-L194) in order to check if the arguments are a chroot.
  * The function [`snapshot_manager.copr_util.get_copr_chroots`](https://github.com/fedora-llvm-team/llvm-snapshots/blob/a597c30d9599811318f95fa47447c591105df6d0/snapshot_manager/snapshot_manager/copr_util.py#L138-L160) returns all chroots we care about. A simple `chroot in get_copr_chroots()` should do the trick.
- [ ] #500

- [x] If all arguments to `/retest` are chroots that we care about, then we should proceed with the actual retest work:

- [x] Remove hidden HTML comment. (e.g. for `fedora-39-x86_64` this could look like `<!--TESTING_FARM:fedora-39-x86_64/8c8fd493-ae3f-4833-878e-71b5697c414c/7309913-->`)
- [x] Re-run (or *call*) the [`check-snapshots.yml` workflow](https://github.com/fedora-llvm-team/llvm-snapshots/blob/a597c30d9599811318f95fa47447c591105df6d0/.github/workflows/check-snapshots.yml). The workflow will notice that all builds are done for (e.g. `fedora-39-x86_64`) in Copr but there's no request ID comment which indicates a testing-farm request. Therefore it will will kick off a testing-farm request automatically. ~~**ALTERNATIVELY:** We could instead file a testing-farm request right away to avoid the huge overhead of running the workflow. This is a call to [`snapshot_manager.testing_farm_util.TestingFarmRequest.make`](https://github.com/fedora-llvm-team/llvm-snapshots/blob/a597c30d9599811318f95fa47447c591105df6d0/snapshot_manager/snapshot_manager/testing_farm_util.py#L149-L220) followed by a flip of the testing labels ([`snapshot_manager.github_util.flip_test_label`](https://github.com/fedora-llvm-team/llvm-snapshots/blob/a597c30d9599811318f95fa47447c591105df6d0/snapshot_manager/snapshot_manager/github_util.py#L428-L457)). The downside is that the whole logic that goes into updating the testing farm results issue not respected and we might end up duplicating work. I vote agains this alternative but I wanted to show it.~~

Here's the whole process as a sequence diagram:

```mermaid
sequenceDiagram
actor author as Comment Author
participant issue as GitHub
participant workflow as GitHub Workflow
participant python as Python script

author ->>+ issue : Request retest through issue comment with:<br />/retest fedora-400-s390x fedora-40-x86_64

activate issue
issue ->> workflow : Trigger retest-GitHub-workflow 
activate workflow

alt Comment author is not a member<br />of the llvm-toolset-engineers team
  workflow ->> issue : Create a comment to notify<br />comment author of illegal operation
  workflow ->> issue : react with thumbs down
  issue --x author : End with failure
  deactivate issue
else Comment author is a member<br />of the llvm-toolset-engineers team
  activate issue
  workflow ->> issue : react with thumbs up
  workflow ->> python : Hand off to python script
  activate python
  loop Check if arguments are chroots we care about
    alt Argument is not a chroot we care about
      python ->> issue : Report about wrong argument
      issue --x author : End with failure
      deactivate issue
    else
     python ->> issue : Remove HTML request ID comment<br /> from issue comment body
     python ->> issue : Call check-snapshots workflow
     python ->> issue : React with rocket
     issue --x author : End with success
    end
    deactivate python
  end
end
deactivate workflow
```

**Comment by tuliom** [comment]
> The workflow should parse comments if they begin with /retest followed by multiple arguments. As soon as this is the case I want to move on from within a Python.

It doesn't hurt to mention: it's also important to check if the comment is coming from one of the people with commit access to this project.

**Comment by kwk** [comment]
> > The workflow should parse comments if they begin with /retest followed by multiple arguments. As soon as this is the case I want to move on from within a Python.
> 
> It doesn't hurt to mention: it's also important to check if the comment is coming from one of the people with commit access to this project.

I think this is implicit because:

> A GitHub workflow that reacts to new comments on issues made by members of this [llvm-toolset-engineers team](https://github.com/orgs/fedora-llvm-team/teams/llvm-toolset-engineers).

Am I not seeing the problem correctly?

**Comment by kwk** [comment]
This commit is here to trigger the retest-GitHub Workflow. It has no other purpose.

/retest chroot1 chroot1

**Comment by kwk** [comment]
This commit is here to trigger the retest-GitHub Workflow. It has no other purpose.

/retest chroot1 chroot1

**Comment by kwk** [comment]
This commit is here to trigger the retest-GitHub Workflow. It has no other purpose.

/retest chroot1 chroot1

**Comment by kwk** [comment]
This commit is here to trigger the retest-GitHub Workflow. It has no other purpose.

/retest chroot1 chroot1

**Comment by kwk** [comment]
Except for #500 and #501 I've implemented everything needed for this feature. Those issues are just improvements and therefore I'll close this original issue.
