### ISSUE TITLE
As a maintainer I want to contribute logs to log-detective

### ISSUE THREAD

**Issue by kwk** [fedora-llvm-team/llvm-snapshots#460]
As a maintainer when looking at logs and what issues we've identified, from time to time I might want to contribute a log file to the [log-detective](https://logdetective.com/).

For example for any given build ID and chroot we can create a link like so:

```
https://logdetective.com/contribute/copr/<8-DIGITS-0-PREFIXED-BUILD-ID>/<CHROOT>
```

For example:

```
https://logdetective.com/contribute/copr/07397509/fedora-38-x86_64
```

Clicking such a link will take you to log-detective where you can annotate you log file with more information.

(Thank you @xsuchy for letting me know how to create the links.)

**Comment by xsuchy** [comment]
note that we have integration in Copr. E.g. see https://copr.fedorainfracloud.org/coprs/g/fedora-llvm-team/llvm-snapshots-incubator-20240502/build/7397653/ the green button on right side.

**Comment by kwk** [comment]
> note that we have integration in Copr. E.g. see https://copr.fedorainfracloud.org/coprs/g/fedora-llvm-team/llvm-snapshots-incubator-20240502/build/7397653/ the green button on right side.

@xsuchy yes, I saw that but it is one step too far away. We have all logs in copr and yet we try to persist the most important snippets in our daily issues for the LLVM snapshot building process ([example](https://github.com/fedora-llvm-team/llvm-snapshots/issues/458#issuecomment-2089425540)).
