### ISSUE TITLE
Get big-merge rpm spec repo in shape to build non-snapshots

### ISSUE THREAD

**Issue by kwk** [fedora-llvm-team/llvm-snapshots#493]
Currently, everything is focussed on building snapshots but some bits are left untouched and need to be updated in order to build released LLVM versions.

Here's a PR that contains a non-exclusive list of updates that we would need:

https://src.fedoraproject.org/rpms/llvm/pull-request/206

**Comment by nikic** [comment]
PR has been merged, so I think this is done...
