### ISSUE TITLE
Get RHEL compat packages in the @fedora-llvm-team/llvm-compat-packages copr repo.

### ISSUE THREAD

**Issue by kwk** [fedora-llvm-team/llvm-snapshots#518]

**Comment by tuliom** [comment]
I built llvm17, clang17 and lld17: https://copr.fedorainfracloud.org/coprs/g/fedora-llvm-team/llvm-compat-packages/monitor/

There is an issue with compiler-rt17, but it shouldn't block testing in this project.

So, I'm closing this.
