### ISSUE TITLE
Merge labels of os and arch into one label

### ISSUE THREAD

**Issue by kwk** [fedora-llvm-team/llvm-snapshots#527]
# Current situation

Currently when a chroot like `fedora-40-x86_64` and `rhel-8-aarch64` fail to build we add these labels to the daily issue: `os/fedora-40`, `arch/x86_64`, `os/rhel-9`, `arch/aarch64`.

# Problem

With the aforementioned labels it becomes impossible to tell if `rhel-9` also failed on `x86_64`.

# Proposal

I think it makes sense to just use the chroot names of a failing build and use them instead. For example: `build_failed/fedora-40-x86_64` `build_failed/rhel-9-aarch64. This would be similar to the labels we assign for `tested_on/fedora-40-x86_64` for example.

In order to not remove the labels from the old issues I suggest we keep the old labels (e.g. `os/fedora-40`) around for a bit longer.

## Open questions:

* Once a chroot (e.g. `fedora-40-x86_64`) is ready to be tested with testing farm, we file a request and put the `in_testing/fedora-40-x86_64` label on the issue. This can be changed into `tested_on/fedora-40-x86_64` (when successful) or `failed_on/fedora-40-x86_64` (for failures). Given this background, I suggest that we have `building_on/fedora-40-x86_64` and `built_on/fedora-40-x86_64` as well. This allows us to see when chroots go EOL for example.

# Tasks

If we can agree to the proposal, these are the tasks necessary:

- [x] #529
- [x] #530

**Comment by nikic** [comment]
The build_failed part of this sounds reasonable to me.

> Once a chroot (e.g. fedora-40-x86_64) is ready to be tested with testing farm, we file a request and put the in_testing/fedora-40-x86_64 label on the issue. This can be changed into tested_on/fedora-40-x86_64 (when successful) or failed_on/fedora-40-x86_64 (for failures). Given this background, I suggest that we have building_on/fedora-40-x86_64 and built_on/fedora-40-x86_64 as well. This allows us to see when chroots go EOL for example.

I'd like this to go the other way, with tested_on being removed, so we only get labels for failure conditions. I don't think having labels for success cases is useful, but it makes the label list a lot longer.

**Comment by kwk** [comment]
For copr builds we only list failed builds with `build_failed_on/<chroot>` now. For testing farm requests being able to be re-run with `retest <chroot>` I wanted to keep the labels the way they are (flipping state).
