### ISSUE TITLE
add lldb to big-merge

### ISSUE THREAD

**Issue by kwk** [fedora-llvm-team/llvm-snapshots#573]

**Comment by kwk** [comment]
With https://github.com/fedora-llvm-team/llvm-snapshots/pull/574 and https://src.fedoraproject.org/rpms/llvm/pull-request/234 being merged we can close this.

**Comment by kwk** [comment]
We still see too many LLDB test failures. Therefore I'm reopening this issue.

**Comment by nikic** [comment]
Filing a new issue to enable lldb tests: https://github.com/fedora-llvm-team/llvm-snapshots/issues/597
