### ISSUE TITLE
Using a more recent llvm-test-suite in tmt tests

### ISSUE THREAD

**Issue by nikic** [fedora-llvm-team/llvm-snapshots#710]
Currently tmt tests will use llvm-test-suite from the corresponding fedora version. This means that getting fixes for llvm-test-suite failures in is a pretty big hassle, because it needs to be done across all supported fedora versions. It would be great if we could use a more recent llvm-test-suite in tmt tests without doing that.

My thinking is that we could either add llvm-test-suite to llvm-compat-builds copr so we can easily feed in a new version through there. Or maybe have a separate copr for llvm-test-suite and add it to the tmt runs explicitly.

**Comment by kwk** [comment]
@nikic this sounds like a good idea. I mean adding it to a similar repo like the compat one or maybe even the same. `llvm-test-suite` is a noarch package so it should be doable without big effort.

**Comment by nikic** [comment]
I've prepared https://src.fedoraproject.org/fork/nikic/rpms/llvm-test-suite/tree/upstream-snapshot with the necessary changes to build an arbitrary commit, and plan to build this into https://copr.fedorainfracloud.org/coprs/g/fedora-llvm-team/llvm-test-suite/. Currently can't get working builds due to some kind of f41/rawhide outage.

For now I'm assuming we can just do an occasional manual build, but if this is a common requirement we can automate it...

**Comment by nikic** [comment]
Closing this as "done". We can reconsider the process here if it turns out we need to regularly update llvm-test-suite.
