### ISSUE TITLE
Lint *.fmf files

### ISSUE THREAD

**Issue by kwk** [fedora-llvm-team/llvm-snapshots#77]
On every PR we should run something like `tmt lint` to check for correctness of `*.fmf` files.

@jchecahi, is there some github action that does this or shall we write our own workflow with a fedora container and `tmt` installed from `psss/tmt` copr?

Documentation: https://tmt.readthedocs.io/en/latest/spec.html

**Comment by kwk** [comment]
This relates to #59

**Comment by jchecahi** [comment]
@kwk I'm not aware of any specific github action which runs `tmt lint`. However, and provided you already have set a pre-commit hook to lint the plans, you might want to set up a [pre-commit action ](https://github.com/pre-commit/action)to be run on each PR.

TMT project itself lint their fmf files this way, check their [action config.](https://github.com/teemtee/tmt/blob/76568c3aee321bd911140bbbe840528849ab74dd/.github/workflows/pre-commit.yml)

**Comment by kwk** [comment]
We now have a [pre-commit setup](519b439778a49e724b7c4b54a2681fb6c252d67c) in place: https://github.com/kwk/llvm-daily-fedora-rpms/blob/main/.pre-commit-config.yaml#L12-L16.

**Comment by kwk** [comment]
Oh, this was for the CI site of things not just pre-commit.
